# Generated by Django 3.2.7 on 2021-11-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dblog', '0002_article_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=0, help_text='削除状態ならTrue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(default=0, help_text='非公開状態ならTrue'),
            preserve_default=False,
        ),
    ]
